export const serviceItems = {
  0: {
    id: "ea1807f2-d0e5-11eb-b8bc-0242ac130003",
    name: "Healthcare",
    desc: "We are blending in the most modern techniques and fascinating possibilities of Virtual reality in healthcare. We are proud to introduce Auticare, the breakthrough technology tool & learning platform for Autism Spectrum Disorder(ASD) and related neurodevelopmental conditions. The platform aims to provide at-home social and communication therapy for autistic children. Auticare can help people with challenges in behaviour, social skills, verbal and non-verbal communication, and sensory and attention issues that impact their lives. The platform can be customised according to the individuals, and the therapists can regularly monitor the progress level daily. According to each scenario, the progress will be stored in the cloud storage, making it easier to evaluate. We are here to help for a better future for your children!",
    img: "/images/services-section/healthcare.jpg",
    link: "https://youtu.be/XFyMoh-8mgk",
    bg: "/images/team-section/team-section-icon-hex-left.svg",
  },
  1: {
    id: "ea1808b0-d0e5-11eb-b8bc-0242ac130003",
    name: "Education",
    desc: "Extend your hands to welcome the next generation in education. We are opening a whole new world of possibilities to students with memorable and immersive experiences using virtual reality. EduoskusXR, our latest cutting-edge platform, creates an entirely digital environment, a 360-degree, immersive user experience that feels real. Here the students will have the provision to share knowledge and understand the latest technologies happening around the globe. The platform provides the opportunity to learn through experience, in contrast to the traditional methods of reading and writing. We bring in proven techniques to raise engagement and increase knowledge retention for students of all ages.",
    img: "/images/services-section/Education.jpg",
    link: "https://youtu.be/UPQS8AF1l9o",
    bg: "/images/team-section/team-section-icon-hex-right.svg",
  },
  2: {
    id: "ea180964-d0e5-11eb-b8bc-0242ac130003",
    name: "Events & Exhibitions",
    desc: "Create truly unforgettable experiences with XR event, a futuristic and interactive virtual event platform, for events and trade shows. We can help you in creating unique and singular experiences for attendees. With XR events, the user can experience an event or trade show altogether without physically being there, which means you can virtually attend an event at the comfort of their homes. The platform provides a 360-degree immersive and engaging experience which helps in providing in-depth information about the product they see on display. It helps you in achieving higher audience engagement with better results in sales.",
    img: "/images/services-section/Event.jpg",
    link: "https://youtu.be/xXGkiE2MEI4",
    bg: "/images/team-section/team-section-icon-hex-left.svg",
  },
  3: {
    id: "ea180b80-d0e5-11eb-b8bc-0242ac130003",
    name: "Tourism",
    desc: "You don’t need a plane ticket to travel the way; now we can help you travel the world without leaving home. We use virtual reality to capture tourism destinations in a unique and immersive way to bring a 360-degree experience. Enjoy your post-pandemic holidays within the comfort of your sofa as our VR technology focuses on the real world rather than computer-generated imagery. Whether you want to transport yourself to different places globally or just hang out together, we can help you. Before booking a hotel, you can have a virtual tour through them. We can also offer the entire booking process and user interface that can be experienced through a virtual reality headset. The future of tourism goes virtual!",
    img: "/images/services-section/Toursim.jpg",
    link: "https://youtu.be/PaaF-Wc4rJA",
    bg: "/images/team-section/team-section-icon-hex-right.svg",
  },
  4: {
    id: "ea180c48-d0e5-11eb-b8bc-0242ac130003",
    name: "Real Estate",
    desc: "Virtual reality is a game-changer in the real estate industry. Our platform can help real estate agents grow their business, get more clients, and deliver top-level services. Embright can help your real estate deals have a global reach as customers can look at the property from anywhere in the world. We bring in an innovative experience that allows the buyers to have a complete virtual view of the property within the comfort of their home. The virtual experience allows the agents to showcase the interiors and exteriors of the property to the clients as if they have a virtual tour. Keeping customers’ convenience in mind, we have developed a unique platform that can be customised according to your needs",
    img: "/images/services-section/Real estate.jpg",
    link: "https://youtu.be/ceqJ0TkZZ8",
    bg: "/images/team-section/team-section-icon-hex-left.svg",
  },
  5: {
    id: "ea180cfc-d0e5-11eb-b8bc-0242ac130003",
    name: "Retail",
    desc: "Embrace the change! The retail industry is reaching new heights with the implementation of virtual reality. Embright can help you create a bridge between the online and real worlds with our immersive virtual reality platform. We can implement fascinating technologies that can enhance the customer experience at any offline store. We use virtual reality to deepen engagement online and increase the footfalls of your store. We can analyse the customer journey and know exactly what the customer needs to create a better shopping experience. We can assist you in building consumer relationships, boosting sales and adding value to the shopper experience.",
    img: "/images/services-section/retail.jpg",
    link: "https://youtu.be/3ew8ikID02o",
    bg: "/images/team-section/team-section-icon-hex-right.svg",
  },
  6: {
    id: "ea180dba-d0e5-11eb-b8bc-0242ac130003",
    name: "Corporate Training",
    desc: "Start upskilling your team! We are here to help you. Embright can help you implement VR as a digital learning strategy to provide an immersive training experience for your employees. We can make each training bespoke to individual teams based on requirements, attendees and corporate culture. We will have a dedicated account manager and 24/7 customer service to ensure the best training experience for corporate clients. VR training pushes the boundaries of traditional learning, which helps employees to learn at their own pace. We can provide increased engagement and better results cost-effectively. For a truly engaging and innovative corporate training experience, you can trust us.",
    img: "/images/services-section/Corporate.jpg",
    link: "",
    bg: "/images/team-section/team-section-icon-hex-left.svg",
  },
  7: {
    id: "ea181030-d0e5-11eb-b8bc-0242ac130003",
    name: "Industry Training",
    desc: "It’s time to approach industrial training using virtual reality technology! Embright brings you a high-end virtual interactive training experience for creating an efficient workforce. We can help you to preserve and institutionalize the workforce knowledge and effectively sustain operational excellence using our VR based training modules based on your industry. With our proven 360-degree total immersion & the simulation of scenarios, we can help your decision-making and learning according to the circumstances. From industries like hospitality, manufacturing and aviation to large scale industries like power generation, our technologies can be used successfully as an efficient way to train their employees cost-effectively. We always make sure that our industry training meets the safety regulations of the respective industry to have the best virtual training experience.",
    img: "/images/services-section/industry.jpg",
    link: "",
    bg: "/images/team-section/team-section-icon-hex-right.svg",
  },
};
